disable -Zmeta-stats since its crashing the compiler thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }', compiler/rustc_metadata/src/rmeta/encoder.rs:781:22